version: 0.1
phases:
  install:
    commands:
      - echo Entered the install phase...
      - aws cloudformation package --template-file template.yaml --output-template-file outputsamtemplate.yaml --s3-bucket ebpfirstbucket 
  artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
